module.exports = {
    rules: {
        "curly": "error",
        "dot-location": ["error", "property"],
        "eqeqeq": ["error", "smart"],
        "guard-for-in": "error",
        "no-alert": "error",
        "no-caller": "error",
        "no-empty-pattern": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-floating-decimal": "error",
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-loop-func": "error",
        "no-multi-spaces": "error",
        "no-multi-str": "error",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-wrappers": "error",
        "no-octal-escape": "error",
        "no-proto": "error",
        "no-return-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-unmodified-loop-condition": "error",
        "no-unused-expressions": "error",
        "no-useless-escape": "error",
        "no-void": "error",
        "no-with": "error",
        "radix": "error",
        "wrap-iife": "error",
        "yoda": ["error", "never"]
    }
};
